[package]
name = "coremidi-sys"
version = "1.0.0"
authors = ["Jonas Klesy", "Patrick Reisert"]
description = "Low-level bindings for the CoreMIDI framework"
license = "MIT"
homepage = "https://github.com/jonas-k/coremidi-sys"

[dependencies]
core-foundation-sys = "0.2"